### ISSUE TITLE
XAsyncGetStatus() no longer returns when called in gdk_quit()

### ISSUE THREAD

**Issue by andrew171717** [YoYoGames/GDKExtension#71]
It's possible this is just happening to me as I have made quite a few changes to my local copy of this extension, but I wanted to bring this up in case anyone else runs into it.

I released my game [Launcher Heroes](https://www.xbox.com/en-US/games/store/launcher-heroes/9nmzhg6wxk01) about 3 months ago on Xbox and Windows. It uses this extension for the Windows release. The game launched smoothly and no issues were present at launch related to the GDK extension. However, at some point in the past few weeks `XAsyncGetStatus(&async, true);` appears to no longer return when called during the execution of `gdk_quit()` causing the game to hang when attempting to close on Windows. This seems odd to me as I have not pushed out any updates to my game and this just started happening to the game in production.

I was able to mitigate the hanging by commenting out `XAsyncGetStatus(&async, true);`. I'm not entirely sure what the consequences are to doing this, but it prevents my game from hanging during closing, so I plan on pushing this out in an update soon.

Edit: I'm specifically referring to this line: https://github.com/YoYoGames/GDKExtension/blob/9dd6c0e9d4cadccdbe0b1a79e6721a6bb04b3094/DLL/GDKExtension/GDKX.cpp#L247

**Comment by DiasFranciscoA** [comment]
The issue should now be resolved in the main branch. To utilize the extension, please ensure you have GDK version 230600 installed.

Please confirm if this rectifies the problem. Be aware that there is no official release available at this time; therefore, you'll need to use the binaries from the main branch.
