### ISSUE TITLE
Old version of GDK

### ISSUE THREAD

**Issue by TERNOX** [YoYoGames/GDKExtension#72]
Hello!

The version of GDK provided here is now outdated. Games with it are not certified by Microsoft.

Simply changing the version from 211000 to 221001 (relevant for the Xbox module) does not help, the project is not built because the XPackageMount function no longer works and it needs to be changed to XPackageMountWithUiAsync.

In fact, this GDK module has not been working for several months.

**Comment by DiasFranciscoA** [comment]
The issue should now be resolved in the main branch. To utilize the extension, please ensure you have GDK version 230600 installed.

Please confirm if this rectifies the problem. Be aware that there is no official release available at this time; therefore, you'll need to use the binaries from the main branch.

**Comment by COWCATGames** [comment]
Hello,
When will there be an official release with this new SDK?

**Comment by COWCATGames** [comment]
Answering myself: I noticed the extension was actually already compiled so just had to download it and replace the extension in my project. Thanks! I needed it for the "simplified user model" which I use on Xbox so didn't want to manage it differently on PC.
