### ISSUE TITLE
Cross-save / Xbox Play Anywhere: is it supposed to work?

### ISSUE THREAD

**Issue by COWCATGames** [YoYoGames/GDKExtension#74]
Hi,

I am adding a GDK PC version to my existing Xbox title. Everything seems to work fine, except the save files aren't the same on both sides. (My title can't "see" the PC saves on the Xbox, and the Xbox can't "see" the PC saves)

Here are the save files I can see on my PC:
![1](https://github.com/YoYoGames/GDKExtension/assets/74605788/674c947f-572c-41db-aa1b-f8f15ce8336c)

The **good** thing is that I *can see* the Xbox save files on my PC. The filenames are garbled but I can open them, they're not encrypted so I can 100% confirm I do retrieve the XBox save files on my PC.

Thus I assume the configuration (user ID, sandbox, SCID) is all correct, or this wouldn't be the case?

The **bad** thing is that they're in a separate folder. (see previous screenshot)
I'd think this is because of a different saving path. But I'm doing relatively the same in both cases (I say "relatively" because the actual functions to call are different)

I am saving my files in a "saves" folder in both cases, which I assume is the "container" name.

The problem is both ways (meaning the Xbox doesn't see my PC files either), and I'm not sure where the save files are located on the Xbox devkit so I can't check if it retrieves the PC files in a separate folder too but I would assume so.

It's only an issue for saves, because the same achievements seem to be unlocked on both sides.

Is there any GameMaker game which actually supports Play Anywhere right now?

Here's my own GameMaker code in both cases, dunno if this would help. My getsavesdir() function simply returns "saves" in both cases.

![winstoresave](https://github.com/YoYoGames/GDKExtension/assets/74605788/2d9abcea-315b-42ec-8aea-add4994dd89b)
![xboxsave](https://github.com/YoYoGames/GDKExtension/assets/74605788/c8306b91-7f96-4d71-b67b-e39ad0779b03)

Can anyone help?

Best,
Fabrice

**Comment by COWCATGames** [comment]
I've found the solution with the XblConnectedStorage tool.
As it turns out, GameMaker saved the Xbox save files inside a container named "root/saves" while my PC save files were saved in "saves". (I never wrote "root" in my code so I assume this is something the Xbox export does automatically)

So the solution was simple: in the PC version I read and save from "root/saves". It works!

Hopefully this might help someone else :)

**Comment by jackerley** [comment]
Glad you got sorted! We'll add something to the documentation

**Comment by gurpreetsinghmatharoo** [comment]
Added note to https://github.com/YoYoGames/GDKExtension/wiki/Storage-Module
and in the Xbox documentation (saving and loading page).
